---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/containers #optional
    volumes:
      - /home/$USER/containers:/containers # Change This
    ports:
      - 8443:8443
    restart: unless-stopped

